language: node_js
node_js:
- '6'
script:
- set -e
- npm test
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/string.ify.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: pOlrBkYHBHHVkVW5kpxRe8cVzuiD5MCBngRdpopOTzmZvrJ61qOym5xoV5S8QHYL450QA+QQym49bkIEkLXN8ctKieCpHgiYBlKnxHxBYx4T834dgKD4RliT4gP9VCO/93Izp+6Fj9FhGUhAup9WITezhylWJLpSgcRGVPUGTvzPzPRUGEAxwch6iqgACLuby2r+C53q6ynO9nW509DxbLA/pqcOeGFFtFtQSc9cO2V88tKskLARggo7G4SZCdmyXaTUL76U+DF5dsms2tM10XuDgm3nq8p4GKZl+QmqMkaFhxZSVeCr45bMF5U+pygqUUJopMidbwVOVhSaGHc4HmdlxTnuU3pgkmoRPPAu5Dkf8B9LL3Yd4YtRTbjKmUWqxy/+TE7gSVZvIU2rSg/gWwt/vB260RfsCVjC7sbvpEwk6PdS9336DoAb4QVI+csogrLVK35T586ul5x7IfbeH2eTF8ZGLL4X/+LsjHnMVPvBG+Jk//caJbDcH4lN/LZwOVfCVgEGxIZE9hDM7whale0xVK9uedq3t9AC3VcjtvhXfQpbXPKn9DXi/hKtQcneJyFwrVHK6v9KGJSo4SqIH+mxqhGxuWVidkTKn3OqhStMITTurhCZ10xwhJIZ7Cwwa0dB6QAAqFY7I35wQy7b0h6RBywfCMTY3ci03n0I+nM=
env:
  global:
  - secure: sppFNHa0uLaapfsdYb8HFTuJlp+PZ1WbWgQjJwLBmfmiv/MFXarq2s4Fvje2RxL4DX4RP105SXH+PJIwUsKgPVU9z0OEhEytsNP70JuWsrn7ALgz0ldgTOmoOGgODtRMwsdUW9b1K5uIcqUqjoaNr4X1eNlK002laod6pZEb9BkBNB+76sPEPm+C+b8xvFBY/g9Km6YY0vjOl1nygpMHaogigHxJYGD5BDRBImYPxW4XIU5KMhFSFaMQu/QH1bngKoMaxT3DBBdvRL0HyxAcDTTzgEc8Ziugtx8q/nP+gjLIgjVYl8/2pIEz7EWbUkoMPq/jCu88PN67vODHtgu/ZG1I+cn3RXKoRbvByt4q97qoaox6vHs3OkKNiPn8Psu4LognhJlADpIJsevZdEQdtOQVWbPLIkyGUgdo/idP8HXb3HwcDLQK7O8VDZfTKQEGpNIHz0z7zrQdTMGjBQ6vSYp7nCVGA1+aPSuy4Ny5QvWXeKYVcCmPpGdHrDL5M0QYx/Gi+rzqCFkXPrcXLaXU+nLuYOIZRImR2zdk+mJxtj7v+52nFW5xiqGcKp0DwJR08nxJZutjAkYtnyQN38ZHcFDPzLGmO+sukW4CFHo8Nx7hKTDSqK2QO15CbTJoXxmOCiIYbeYqO56PcX5ForW+v/F2FwUyBld58wQjp3a2fnY=
