language: node_js
node_js:
- '6'
script:
- set -e
- npm test
- npm run coveralls
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- npm config set git-tag-version=false
- NPM_VERSION=$(npm version patch)
- git commit -a -m "${NPM_VERSION:1}" -m "[ci skip]"
- git remote remove origin
- git remote add origin https://${GITHUB_TOKEN}@github.com/xpl/string.ify.git
- git push origin HEAD:master
deploy:
  provider: npm
  email: rocket.mind@gmail.com
  api_key:
    secure: iLiAvcQsDmRDAAeHAj+BVZ1ecx9PHOOCZhLZUmATfBDGHNeJOmIkrry9AZUSpqctD533aHJ3AauGRbBeSFl68GHVWzDXe6Ocai1WuX8gYTwOrJG+WSdD3TcG76CBkpiH7LhLQV0pCuPhjUShQfwB1knnzDDriJ6kJbQbD5xE9s36tVUgwRwmSCNxKoLNrgdy3rs8M+BQyKCes0l3OE8kOkZNwpRX2MR90Bb6NycuY58pP2GcG8ploQyC5X0r1FvQlvDZmfmEpszmSc+DYCNEgEEDD60mVIQTRu+RvQpzBe/ps/ZwK/v7nZGHcWeDAlyYdQGUXJIX+ZT/iI3q0AyeCETtJ2FeDrQdW4K/nFtqZM/jgZk+Lxa9q5JL9uMHXtATxJF4Jz/TOGSyMhujNtI9gfPuDPv5pBpF/aktpuhOnuDMR18qp1HOPat5B2e1p60EZfeevxDAhmQQg1CUtks+zh5ZBSLxQNbg4ARTR7xX2wyh2pysVaKE4ufZ7wXZjgc5cwej4cRizE4yxs6QyTHq311lhHKFPj5ju/XMO/hAt5vYmf6GCyZ5SuhzgHhLExkFq0wDdgbd6QTK6gJnwfbYvHa1nkQRPzRkBCNraaXR+O3xzstw5ogVB+8PWlHOKDiXvVZOhVi+UjTsvmarmNQTl1g0kkByI9y2S8Lh+UfBPwU=
env:
  global:
  - secure: sppFNHa0uLaapfsdYb8HFTuJlp+PZ1WbWgQjJwLBmfmiv/MFXarq2s4Fvje2RxL4DX4RP105SXH+PJIwUsKgPVU9z0OEhEytsNP70JuWsrn7ALgz0ldgTOmoOGgODtRMwsdUW9b1K5uIcqUqjoaNr4X1eNlK002laod6pZEb9BkBNB+76sPEPm+C+b8xvFBY/g9Km6YY0vjOl1nygpMHaogigHxJYGD5BDRBImYPxW4XIU5KMhFSFaMQu/QH1bngKoMaxT3DBBdvRL0HyxAcDTTzgEc8Ziugtx8q/nP+gjLIgjVYl8/2pIEz7EWbUkoMPq/jCu88PN67vODHtgu/ZG1I+cn3RXKoRbvByt4q97qoaox6vHs3OkKNiPn8Psu4LognhJlADpIJsevZdEQdtOQVWbPLIkyGUgdo/idP8HXb3HwcDLQK7O8VDZfTKQEGpNIHz0z7zrQdTMGjBQ6vSYp7nCVGA1+aPSuy4Ny5QvWXeKYVcCmPpGdHrDL5M0QYx/Gi+rzqCFkXPrcXLaXU+nLuYOIZRImR2zdk+mJxtj7v+52nFW5xiqGcKp0DwJR08nxJZutjAkYtnyQN38ZHcFDPzLGmO+sukW4CFHo8Nx7hKTDSqK2QO15CbTJoXxmOCiIYbeYqO56PcX5ForW+v/F2FwUyBld58wQjp3a2fnY=
  - secure: gSBwwq4lLEtu5c/WldrqWaiibYTMG3XSZdaTlLtee5rBEvajFrZYub3ww3LLVmFgWsfaXFj/LUrwStaOo3sGTKLPj4Qxks/jpJy8sze+o6pTHskjmjps+W4sHhpxT3kB1VdTkjpwG/0xbV1/zqn9iImXrhjkj8N6Tcc3e4QSoVFezl/CgBV4Y8QMUyOg/iJZ/7YPbDd2oj2/SfUJsj8+9JSitvl3ksf3ucGpvsqAmCLt3vBB2ymVDMXjUEati+aJoGPJ+n/8FjVYrjPaVPv5Kyq8Q3uFp7o7LpFn7yijmt3d+I9i6g8tBEcGNN9gEqQcQxChQzcDNbQX2r1OGwL3x0cD/Y2n0NV1BpjdIskQa3LgAbRP60NOJsrmnCCIUA81h4UMTAVsxUSrb8GsAmXn6QfsnjnM47Vd3zkVGYrCEHIUlVV/LjgPpVrUfb1gSJwgZ1n8/v0cQ6HbDnSspnawXkyxga/R1xtQvtCeOVku1Orvav7agKUUJjUgvMLMLFBnUfM3mvrUVs/OAAEEJM/618YVDoKlKLsGl9kMqTpzs52M5PQqOkBtOFPvZ36N9/ohwB4nBGY6IRjpba1Nv5aNns0edcMj+PzePupNLkax8mq8QGhZiSUfnkHvftcqBluwnGnF//pM8H9uXJumZf4IZCs6BdinsM2imZ5B5q1naVo=
